# Form implementation generated from reading ui file 'Story_Screen2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow22(object):
    def setupUi(self, MainWindow22):
        MainWindow22.setObjectName("MainWindow22")
        MainWindow22.resize(300, 450)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow22)
        self.centralwidget.setObjectName("centralwidget")
        self.label_s_header2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_s_header2.setGeometry(QtCore.QRect(30, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_s_header2.setFont(font)
        self.label_s_header2.setObjectName("label_s_header2")
        self.text_s_story = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.text_s_story.setGeometry(QtCore.QRect(20, 160, 251, 201))
        self.text_s_story.setObjectName("text_s_story")
        self.text_s_title = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.text_s_title.setGeometry(QtCore.QRect(80, 80, 201, 20))
        self.text_s_title.setObjectName("text_s_title")
        self.label_s_story = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_s_story.setGeometry(QtCore.QRect(110, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_s_story.setFont(font)
        self.label_s_story.setObjectName("label_s_story")
        self.button_s_finish = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_s_finish.setGeometry(QtCore.QRect(100, 370, 75, 23))
        self.button_s_finish.setObjectName("button_s_finish")
        self.label_s_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_s_title.setGeometry(QtCore.QRect(20, 80, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_s_title.setFont(font)
        self.label_s_title.setObjectName("label_s_title")
        MainWindow22.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow22)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow22.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow22)
        self.statusbar.setObjectName("statusbar")
        MainWindow22.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow22)
        QtCore.QMetaObject.connectSlotsByName(MainWindow22)

    def retranslateUi(self, MainWindow22):
        _translate = QtCore.QCoreApplication.translate
        MainWindow22.setWindowTitle(_translate("MainWindow22", "MainWindow"))
        self.label_s_header2.setText(_translate("MainWindow22", "New Entry"))
        self.label_s_story.setText(_translate("MainWindow22", "Story:"))
        self.button_s_finish.setText(_translate("MainWindow22", "Finish"))
        self.label_s_title.setText(_translate("MainWindow22", "Title:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow22 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow22()
    ui.setupUi(MainWindow22)
    MainWindow22.show()
    sys.exit(app.exec())
