# Form implementation generated from reading ui file 'Story_Screen1.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow21(object):
    def setupUi(self, MainWindow21):
        MainWindow21.setObjectName("MainWindow21")
        MainWindow21.resize(300, 450)
        MainWindow21.setMinimumSize(QtCore.QSize(300, 450))
        MainWindow21.setMaximumSize(QtCore.QSize(300, 450))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow21)
        self.centralwidget.setObjectName("centralwidget")
        self.label_s_header1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_s_header1.setGeometry(QtCore.QRect(20, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_s_header1.setFont(font)
        self.label_s_header1.setObjectName("label_s_header1")
        self.button_s_new_entry = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_s_new_entry.setGeometry(QtCore.QRect(90, 140, 75, 23))
        self.button_s_new_entry.setObjectName("button_s_new_entry")
        self.button_s_view_entries = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_s_view_entries.setGeometry(QtCore.QRect(90, 190, 75, 23))
        self.button_s_view_entries.setObjectName("button_s_view_entries")
        MainWindow21.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow21)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 300, 21))
        self.menubar.setObjectName("menubar")
        MainWindow21.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow21)
        self.statusbar.setObjectName("statusbar")
        MainWindow21.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow21)
        QtCore.QMetaObject.connectSlotsByName(MainWindow21)

    def retranslateUi(self, MainWindow21):
        _translate = QtCore.QCoreApplication.translate
        MainWindow21.setWindowTitle(_translate("MainWindow21", "MainWindow"))
        self.label_s_header1.setText(_translate("MainWindow21", "Story App"))
        self.button_s_new_entry.setText(_translate("MainWindow21", "New Entry"))
        self.button_s_view_entries.setText(_translate("MainWindow21", "View Entries"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow21 = QtWidgets.QMainWindow()
    ui = Ui_MainWindow21()
    ui.setupUi(MainWindow21)
    MainWindow21.show()
    sys.exit(app.exec())
